ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: python3 -m pip install planemo galaxy-language-server
  command: python3 -m pip install planemo galaxy-language-server
github:
    prebuilds:
        pullRequestsFromForks: true
