name: bia_download
owner: bgruening
categories:
  - Imaging
description: Tool to query ftp links for study from BioImage Archive
long_description: A wrapper that Curl's FTP links with studies from the BioImage Archive (https://www.ebi.ac.uk/bioimage-archive/). 
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/bia-ftplinks
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "A Tool to query ftp links by study name(s) from the BioImage Archive."
