name: blobToolKit
owner:  Richard Challis, Edward Richards, Jeena Rajan, Guy Cochrane, Mark Blaxter
description: genome assembly QC
homepage_url: https://blobtoolkit.genomehubs.org/
long_description: |
  It is a command line tool designed to aid genome assembly QC and contaminant/cobiont detection and filtering.
remote_repository_url: https://github.com/blobtoolkit/blobtoolkit
categories:
- Quality Control
